import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/common/Navbar'
import Stats from '../components/LendAndBorrow/Stats'
import RightDetails from '../components/LendAndBorrow/RightDetails'

const Home: NextPage = () => {
  return (
    <div className="bg-dark-primary h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-body mx-auto">
        <Navbar />
        <h5 >{`< Back / Lend & Borrow / SOL`}</h5>
        <main className="flex justify-between">
          <Stats />
          <RightDetails />
        </main>
      </div>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}

export default Home
